### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Hazwang** [PolicyAnalysisInc/heRoMod#11]
I could not install the package.

![image](https://user-images.githubusercontent.com/71687279/93846845-d3cfca80-fcd7-11ea-8d94-c5128b2f7068.png)

**Comment by jrdnmdhl** [comment]
Hi @Hazwang. It appears that your version of R isn't able to handle a few unicode characters in the source code of heRomod. I have replaced those unicode characters with escape sequences. Please try to install again and let me know how it goes.

**Comment by Hazwang** [comment]
Hi @jrdnmdhl. 

![image](https://user-images.githubusercontent.com/71687279/93890653-2a132c80-fd1d-11ea-9771-04e3bcac5d4f.png)

**Comment by jrdnmdhl** [comment]
Can you check what character encoding you are currently using in Rstudio? Try setting the encoding to UTF-8 and running again. See link below for info on setting character encoding:

https://support.rstudio.com/hc/en-us/articles/200532197-Character-Encoding

**Comment by jrdnmdhl** [comment]
I should add, the section I'm referencing in that article is "Setting the Default Encoding".

**Comment by Hazwang** [comment]
I did change the default text encoding to UTF-8 but nothing works for me.

![image](https://user-images.githubusercontent.com/71687279/93900824-6c8e3680-fd28-11ea-9cc7-0f3974d90c46.png)

**Comment by jrdnmdhl** [comment]
After getting access to a Windows machine I was able to reproduce the issue. Running `Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")` before installing appears to allow the installation to move forward.
