### ISSUE TITLE
Install Command 

### ISSUE THREAD

**Issue by jflevy** [PolicyAnalysisInc/heRoMod#3]
The install line currently does not work, it should be: 

devtools::install_github("PolicyAnalysisInc/heRomod")

May also want to add: 
install.packages("devtools")
library(devtools)

**Comment by jrdnmdhl** [comment]
Hi Joe, thanks for the comment. I have updated the readme to include commands that will install the necessary packages to install heRomod. I also changed it to used the `remotes` package instead of `devtools` since it has viewer dependencies and will be easier for people to install.
